Src/ITS.Website/ITS.Admin/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ITS.Business.Abstract;
using ITS.Domain.Models.Bus;
using ITS.Domain.Entities;
using ITS.Domain.Entities.Extensions;
using ITS.Domain.Models.Bus.Admin;

namespace ITS.Admin.Controllers
{
    public class BusController : Controller
    {
        private readonly IBusService busService;
        public BusController(IBusService busService)
        {
            this.busService = busService;
        }
        //
        // GET: /Bus/

        public ActionResult Index()
        {
            BusRouteInfoViewModel model = new BusRouteInfoViewModel();
            model.RouteSelectList = new SelectList(BuildRouteSelectList(busService.GetAllBusRoutes()), "Value", "Text");
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            BusRouteInfoViewModel model = new BusRouteInfoViewModel();
            if (TryUpdateModel<BusRouteInfoViewModel>(model))
            {
                return RedirectToAction("EditBus", new { ID = model.SelectedRoute });
            }
            model.RouteSelectList = new SelectList(BuildRouteSelectList(busService.GetAllBusRoutes()), "Value", "Text");
            return View(model);
        }
        private IList<SelectListItem> BuildRouteSelectList(IList<BusRoute> routes)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var r in routes)
            {
                items.Add(new SelectListItem
                {
                    Text = r.RouteName,
                    Value = r.RouteID.ToString()
                });
            }

            return items;
        }

        public ActionResult EditBus(Guid ID)
        {
            EditBusViewModel model = new EditBusViewModel();
            model.RouteID = ID;
            return View(model);
        }

        public ActionResult BusRouteList()
        {
            BusRouteListViewModel model = new BusRouteListViewModel();
            model.BusRouteList = BuildBusRouteListModel(busService.GetAllBusRoutes());
            return View(model);
        }

        [HttpPost]
        public ActionResult BusRouteList(FormCollection collection)
        {
            BusRouteListViewModel model = new BusRouteListViewModel();
            if (TryUpdateModel<BusRouteListViewModel>(model))
            {
                foreach (BusRouteModel r in model.BusRouteList)
                {
                    busService.SaveBusRoute(new BusRoute() { RouteID = r.RouteID, RouteName = r.RouteName });
                }
                if (!string.IsNullOrEmpty(model.NewBusRoute))
                {
                    busService.InsertBusRoute(new BusRoute() { RouteName = model.NewBusRoute });
                }
                return RedirectToAction("BusRouteList");
            }
            return View(model);
        }
        private IList<BusRouteModel> BuildBusRouteListModel(IList<BusRoute> iList)
        {
            IList<BusRouteModel> list = new List<BusRouteModel>();
            foreach (BusRoute r in iList)
            {
                list.Add(new BusRouteModel() { RouteID = r.RouteID, RouteName = r.RouteName });
            }
            return list;
        }
        #region Road
        public ActionResult RoadList()
        {
            RoadListViewModel model = new RoadListViewModel();
            model.RoadList = BuildRoadListModel(busService.GetAllRoads());
            return View(model);
        }

        [HttpPost]
        public ActionResult RoadList(FormCollection collection)
        {
            RoadListViewModel model = new RoadListViewModel();
            if (TryUpdateModel<RoadListViewModel>(model))
            {
                foreach (RoadModel r in model.RoadList)
                {
                    busService.SaveRoad(new Road() { RoadID = r.RoadID, RoadName = r.RoadName });
                }
                if (!string.IsNullOrEmpty(model.NewRoad))
                {
                    busService.InsertRoad(new Road() { RoadName = model.NewRoad });
                }
                return RedirectToAction("RoadList");
            }
            return View(model);
        }
        private IList<RoadModel> BuildRoadListModel(IList<Road> iList)
        {
            IList<RoadModel> list = new List<RoadModel>();
            foreach (Road r in iList)
            {
                list.Add(new RoadModel() { RoadID = r.RoadID, RoadName = r.RoadName });
            }
            return list;
        }
        public ActionResult DeleteRoad(Guid ID)
        {
            DeleteRoadViewModel model = new DeleteRoadViewModel() { RoadID = ID };
            return View(model);
        }

        [HttpPost]
        public ActionResult DeleteRoad(FormCollection collection)
        {
            DeleteRoadViewModel model = new DeleteRoadViewModel();
            if (TryUpdateModel<DeleteRoadViewModel>(model))
            {
                busService.DeleteRoad(model.RoadID);
                return RedirectToAction("RoadList");
            }
            return View(model);
        }
        #endregion

        #region RoadSession
        public ActionResult RoadSession(Guid ID)
        {
            RoadSessionViewModel model = BuildRoadSessionViewModel(busService.GetRoadSession(ID));
            return View(model);
        }
        [HttpPost]
        public ActionResult RoadSession(FormCollection collection)
        {
            RoadSessionViewModel model = new RoadSessionViewModel();
            if (TryUpdateModel<RoadSessionViewModel>(model))
            {
                RoadSession rs = new RoadSession()
                {
                    ID = model.ID,
                    RoadID = model.RoadID,
                    AddressLower = model.AddressLower,
                    AddressUpper = model.AddressUpper,
                    Description = model.Description,
                    PositionLower = new Point() { lat = model.PositionLower_X, lng = model.PositionLower_Y },
                    PositionUpper = new Point() { lat = model.PositionUpper_X, lng = model.PositionUpper_Y }
                };
                busService.SaveRoadSession(rs);
            }
            return View(model);
        }
        private RoadSessionViewModel BuildRoadSessionViewModel(RoadSession roadSession)
        {
            RoadSessionViewModel model = new RoadSessionViewModel()
            {
                ID = roadSession.ID,
                RoadID = roadSession.RoadID,
                AddressLower = roadSession.AddressLower,
                AddressUpper = roadSession.AddressUpper,
                Description = roadSession.Description,
                PositionLower_X = roadSession.PositionLower.lng,
                PositionLower_Y = roadSession.PositionLower.lat,
                PositionUpper_X = roadSession.PositionUpper.lng,
                PositionUpper_Y = roadSession.PositionUpper.lat
            };
            return model;
        }
        private IList<RoadSessionViewModel> BuildRoadSessionListViewModel(IList<RoadSession> iList)
        {
            IList<RoadSessionViewModel> list = new List<RoadSessionViewModel>();
            foreach (RoadSession r in iList)
            {
                list.Add(BuildRoadSessionViewModel(r));
            }
            return list;
        }
        public ActionResult RoadSessionList(Guid ID)
        {
            RoadSessionListViewModel model = new RoadSessionListViewModel()
            {
                RoadSessionList = BuildRoadSessionListViewModel(busService.GetAllRoadSessionOfARoad(ID)),
                RoadID = ID
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult RoadSessionList(FormCollection collection)
        {
            RoadSessionListViewModel model = new RoadSessionListViewModel();
            if (TryUpdateModel<RoadSessionListViewModel>(model))
            {
                foreach (RoadSessionViewModel r in model.RoadSessionList)
                {
                    RoadSession rs = new RoadSession()
                    {
                        ID = r.ID,
                        RoadID = r.RoadID,
                        AddressLower = r.AddressLower,
                        AddressUpper = r.AddressUpper,
                        Description = r.Description,
                        PositionLower = new Point() { lng = r.PositionLower_X, lat = r.PositionLower_Y },
                        PositionUpper = new Point() { lng = r.PositionUpper_X, lat = r.PositionUpper_Y }
                    };
                    busService.SaveRoadSession(rs);
                }

                return RedirectToAction("RoadSessionList");
            }
            return View(model);
        }

        public ActionResult AddRoadSession(Guid ID)
        {
            RoadSessionViewModel model = new RoadSessionViewModel();
            model.RoadID = ID;
            return View(model);
        }
        [HttpPost]
        public ActionResult AddRoadSession(FormCollection collection)
        {
            RoadSessionViewModel model = new RoadSessionViewModel();
            if (TryUpdateModel<RoadSessionViewModel>(model))
            {
                /*Insert new session*/
                RoadSession nrs = new RoadSession()
                {
                    ID = Guid.NewGuid(),
                    RoadID = model.RoadID,
                    AddressLower = model.AddressLower,
                    AddressUpper = model.AddressUpper,
                    Description = model.Description,

Src/ITS.Website/ITS.Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITS.Admin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Src/ITS.Website/ITS.Admin/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

Src/ITS.Website/ITS.Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<!-- gadget left 1 -->
<!-- gadget left 2 -->
<div class="gadget">
    <div class="titlebar vertsortable_head">
        <a href="#" class="hidegadget" rel="hide_block">
            <img src="images/spacer.gif" alt="picture" width="19" height="33" /></a>
        <h3 class="centerText">
            THAO TÁC THƯỜNG DÙNG</h3>
    </div>
    <div class="gadgetblock">
        <div class="iconblockpar">
            <div class="iconblockshade">
                <div class="blockshadow">
                    <div class="bs_content iconblock">
                        <p>
                            <a href="@Url.Action("BusRouteList", "Bus")">
                                <img src="images/img_1.jpg" width="64" height="64" alt="Admin Box" /></a><br />
                            <a href="@Url.Action("BusRouteList", "Bus")">Tuyến xe</a></p>
                    </div>
                </div>
            </div>
            <div class="iconblockshade">
                <div class="blockshadow">
                    <div class="bs_content iconblock">
                        <p>
                            <a href="@Url.Action("RoadList", "Bus")">
                                <img src="images/img_5.jpg" width="64" height="64" alt="Web Box" /></a><br />
                            <a href="@Url.Action("RoadList", "Bus")">Đường</a></p>
                    </div>
                </div>
            </div>
            <div class="iconblockshade">
                <div class="blockshadow">
                    <div class="bs_content iconblock">
                        <p>
                            <a href="@Url.Action("BusStationList", "Bus")">
                                <img src="images/img_2.jpg" width="64" height="64" alt="Art Box" /></a><br />
                            <a href="@Url.Action("BusStationList", "Bus")">Trạm xe</a></p>
                    </div>
                </div>
            </div>
            <div class="iconblockshade">
                <div class="blockshadow">
                    <div class="bs_content iconblock">
                        <p>
                            <a href="#">
                                <img src="images/img_7.jpg" width="64" height="64" alt="Art Line" /></a><br />
                            <a href="#">Contact Us</a></p>
                    </div>
                </div>
            </div>
            <div class="iconblockshade">
                <div class="blockshadow">
                    <div class="bs_content iconblock">
                        <p>
                            <a href="#">
                                <img src="images/img_3.jpg" width="64" height="64" alt="Web Box" /></a><br />
                            <a href="#">Web Box</a></p>
                    </div>
                </div>
            </div>
            <div class="clr">
            </div>
        </div>
    </div>
</div>
<!-- gadget left 3 -->
<div class="gadget">
    <div class="titlebar vertsortable_head">
        <a href="#" class="hidegadget" rel="hide_block">
            <img src="images/spacer.gif" alt="picture" width="19" height="33" /></a>
        <h3>
            CẢNH BÁO</h3>
    </div>
    <div class="gadgetblock">
        <h2>
            Bạn là quản trị web?</h2>
        <p class="light">
            Bạn đang truy cập vào trang quản trị hệ thống website của BKG (BK Group).</p>
        <div class="linehr">
        </div>
        <p>
            Hệ thống này là tài sản của BKG. Nếu bạn chưa được cho phép (bằng email) của Ban
            Điều Hành thì vui lòng thoát khỏi hệ thống ngay lập tức, nếu không bạn phải chịu
            trách nhiệm pháp lý cho những thông tin trên hệ thống này!</p>
        <p>
            Mọi hoạt động của bạn đều đang được theo dõi!</p>
    </div>
</div>
<!-- gadget left 5 -->
<div class="gadget">
    <div class="titlebar vertsortable_head">
        <a href="#" class="hidegadget" rel="hide_block">
            <img src="images/spacer.gif" alt="picture" width="19" height="33" /></a>
        <h3>
            Thông tin hỗ trợ</h3>
    </div>
    <div class="gadgetblock">
        <form action="" method="post" id="form_userstable">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="gwlines">
            <tr>
                <th width="40">
                    <input name="utc1" id="utc1" type="checkbox" />
                </th>
                <th width="150">
                    Tên
                </th>
                <th width="150">
                    Mobile
                </th>
                <th>
                    E-mail
                </th>
            </tr>
            <tr>
                <td>
                    <input name="utc3" id="Checkbox1" type="checkbox" />
                </td>
                <td>
                    Văn Đức Sơn Hà
                </td>
                <td>
                    (+84) 1223.937.937
                </td>
                <td>
                    <a href="mailto:vanducsonha@gmail.com">vanducsonha@gmail.com</a>
                </td>
            </tr>
            <tr>
                <td>
                    <input name="utc3" id="Checkbox1" type="checkbox" />
                </td>
                <td>
                    Hồ Quốc Phong
                </td>
                <td>
                    (+84) 902 384 315
                </td>
                <td>
                    <a href="mailto:phongmt02bk@gmail.com">phongmt02bk@gmail.com</a>
                </td>
            </tr>
            <tr class="last">
                <td>
                    <input name="utc4" id="utc4" type="checkbox" />
                </td>
                <td>
                    Nguyễn Hồng Huấn
                </td>
                <td>
                    (+84) 906 028 243
                </td>
                <td>
                    <a href="mailto:huan.nguyen.playsoft@gmail.com">huan.nguyen.playsoft@gmail.com</a>
                </td>
            </tr>
        </table>
        </form>
    </div>
</div>